#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww` # TODO: this doesnt work when used with sxhkd ?

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	/home/josht/bin/eww --config "$CFG" daemon
	sleep 3
fi

## Open widgets 
run_eww() {
    /home/josht/bin/eww --config "$CFG" open-many \
		   profile \
		   system \
		   clock \
           music \
           weather \
		   uptime \
		   github \
		   reddit \
		   twitter \
		   youtube \
           asu \
		   apps \
		   folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
    /home/josht/bin/eww	--config "$CFG" close \
					profile system clock uptime github \
					reddit twitter youtube apps folders music weather asu
	rm "$FILE"
fi
