#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="firefox --new-tab"

close_dash() {
	/home/josht/bin/eww --config "$CFG" close \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders asu profile music \
                    github system clock uptime
	rm -rf "$FILE"
}

if [[ "$1" == "--mail" ]]; then
	close_dash && ${cmd} "https://mail.google.com"

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--rd" ]]; then
	close_dash && ${cmd} "https://reddit.com"

elif [[ "$1" == "--tw" ]]; then
	close_dash && ${cmd} "https://twitter.com"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"
elif [[ "$1" == "--asu" ]]; then
    close_dash && ${cmd} "https://my.asu.edu"
fi
