#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

dunst &
# start polybar
./.config/polybar/launch.sh &

# wallpaper
nitrogen --set-scaled Pictures/giyu.png 

bspc config focused_border_color "#20dbfa"

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
