#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

# start sxhkd in background
# sxhkd & # is this necessary? testing if not

# start polybar
./startbt21bar.sh

# start compton the compositor
# todo: replace this with picom since picom is maintained now
compton &

# start wallpaper
nitrogen --set-scaled Pictures/sage.png

# colors
bspc config focused_border_color "#e9c5ff"
bspc config normal_border_color "#364966"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Chromium desktop='^2'
