#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall -q polybar
polybar bspwm-edg &
nitrogen --restore &

killall -q picom
picom --experimental-backends &

killall -q nm-applet
nm-applet &

killall -q flameshot
flameshot &

killall -q dunst
dunst &

bspc monitor -d I II III IV V

bspc config focused_border_color "#d90420"
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
